"""Signal Engine — Rule-based signal detection using EMA crossover + RSI.

Detects trade opportunities when EMA(fast) crosses EMA(slow), confirmed by
RSI not being in overbought/oversold territory. Enforces guard conditions:
warm-up period, session window, spread limit, and one-position-at-a-time.

Requirements: 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8
"""
from dataclasses import dataclass
from datetime import datetime
from typing import Optional

from app.config import Settings
from app.indicators.ema import calculate_ema
from app.indicators.rsi import calculate_rsi


@dataclass
class Signal:
    """Trade signal generated by the Signal Engine."""

    direction: str  # "BUY" or "SELL"
    entry_price: float
    stop_loss: float
    take_profit: float


@dataclass
class Tick:
    """Current market tick data."""

    bid: float
    ask: float
    spread: int  # in points


@dataclass
class Candle:
    """Single candle from the candle buffer."""

    close: float


def is_in_session(utc_now: datetime, settings: Settings) -> bool:
    """Check if current UTC time is within the trading session window.

    Returns True if the hour is within London OR New York session.

    Args:
        utc_now: Current UTC datetime.
        settings: Application settings with session hour boundaries.

    Returns:
        True if within at least one active session.
    """
    hour = utc_now.hour
    in_london = settings.london_start_hour <= hour < settings.london_end_hour
    in_ny = settings.ny_start_hour <= hour < settings.ny_end_hour
    return in_london or in_ny


class SignalEngine:
    """Rule-based signal engine using EMA crossover + RSI confirmation.

    All logic is contained in the `check_signal` method which is a pure
    function (no side effects, no I/O) — making it easily testable.
    """

    def check_signal(
        self,
        candles: list[Candle],
        current_tick: Tick,
        utc_now: datetime,
        has_open_position: bool,
        settings: Settings,
    ) -> Optional[Signal]:
        """Check for a trade signal based on current market conditions.

        Guard conditions (any failing returns None):
        1. Warm-up: need at least ema_slow_period candles
        2. Session: must be within London or New York session
        3. Spread: must be below max_spread_points
        4. No open position (one position at a time)

        Signal logic:
        - BUY: EMA fast crosses above EMA slow AND RSI < overbought
        - SELL: EMA fast crosses below EMA slow AND RSI > oversold

        Args:
            candles: List of recent candles (chronological, most recent last).
            current_tick: Latest market tick with bid/ask/spread.
            utc_now: Current UTC datetime.
            has_open_position: Whether a position is currently open.
            settings: Application settings with indicator/trading parameters.

        Returns:
            Signal dataclass if conditions are met, None otherwise.
        """
        # Guard 1: Warm-up period
        if len(candles) < settings.ema_slow_period:
            return None

        # Guard 2: Session window
        if not is_in_session(utc_now, settings):
            return None

        # Guard 3: Spread filter
        if current_tick.spread >= settings.max_spread_points:
            return None

        # Guard 4: One position at a time
        if has_open_position:
            return None

        # Calculate indicators
        closes = [c.close for c in candles]
        ema_fast = calculate_ema(closes, settings.ema_fast_period)
        ema_slow = calculate_ema(closes, settings.ema_slow_period)
        rsi = calculate_rsi(closes, settings.rsi_period)

        # Need at least 2 EMA values for crossover detection and 1 RSI value
        if len(ema_fast) < 2 or len(ema_slow) < 2 or len(rsi) < 1:
            return None

        # Crossover detection — align from the end
        prev_fast, curr_fast = ema_fast[-2], ema_fast[-1]
        prev_slow, curr_slow = ema_slow[-2], ema_slow[-1]

        direction: Optional[str] = None

        # Golden cross: fast crosses above slow
        if prev_fast <= prev_slow and curr_fast > curr_slow:
            if rsi[-1] < settings.rsi_overbought:
                direction = "BUY"
        # Death cross: fast crosses below slow
        elif prev_fast >= prev_slow and curr_fast < curr_slow:
            if rsi[-1] > settings.rsi_oversold:
                direction = "SELL"

        if direction is None:
            return None

        # Construct signal with entry price, SL, and TP
        entry_price = current_tick.ask if direction == "BUY" else current_tick.bid
        point = 0.01  # XAUUSD point size
        sl_distance = settings.stop_loss_points * point
        tp_distance = settings.take_profit_points * point

        if direction == "BUY":
            stop_loss = entry_price - sl_distance
            take_profit = entry_price + tp_distance
        else:
            stop_loss = entry_price + sl_distance
            take_profit = entry_price - tp_distance

        return Signal(
            direction=direction,
            entry_price=entry_price,
            stop_loss=stop_loss,
            take_profit=take_profit,
        )
