"""Trade Orchestrator — Coordinate signal → command construction pipeline.

Constructs Trade_Command from signals using configured lot_size.
Records pending trades in Redis and updates based on execution results.

Key invariant: command.lot_size ALWAYS equals settings.lot_size.

Requirements: 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7
"""
import json

from app.config import Settings
from app.models.enums import CommandType
from app.models.responses import TradeCommand
from app.services.signal_engine import Signal


class TradeOrchestrator:
    """Coordinates signal detection → trade command construction.

    Responsible for:
    - Constructing Trade_Command from Signal using configured lot_size
    - Recording pending trades in Redis
    - Updating trade status based on execution results
    """

    def __init__(self, redis, settings: Settings):
        self._redis = redis
        self._settings = settings

    def construct_trade_command(self, signal: Signal) -> TradeCommand:
        """Construct a Trade_Command from a signal using configured lot_size.

        lot_size always = settings.lot_size (Property 4 invariant).
        SL/TP come from the signal (already computed by SignalEngine).

        Args:
            signal: Signal generated by the SignalEngine.

        Returns:
            TradeCommand with direction, lot_size, stop_loss, take_profit.
        """
        return TradeCommand(
            type=CommandType.BUY if signal.direction == "BUY" else CommandType.SELL,
            lot_size=self._settings.lot_size,
            stop_loss=signal.stop_loss,
            take_profit=signal.take_profit,
        )

    async def record_pending_trade(self, command: TradeCommand) -> None:
        """Record trade as PENDING in Redis.

        Full PostgreSQL recording comes in Wave 6.

        Args:
            command: The trade command being sent to the EA.
        """
        await self._redis.set(
            "trade:pending",
            json.dumps({
                "type": command.type.value,
                "lot_size": command.lot_size,
                "stop_loss": command.stop_loss,
                "take_profit": command.take_profit,
                "status": "PENDING",
            }),
        )

    async def record_trade_result(
        self,
        success: bool,
        ticket: int = None,
        fill_price: float = None,
        error_code: int = None,
    ) -> None:
        """Update trade status based on execution result.

        On success: sets a success flag for StateManager to consume.
        On failure: removes the success flag.
        Always clears the pending trade record.

        Args:
            success: Whether the trade executed successfully.
            ticket: MT5 ticket number (on success).
            fill_price: Actual fill price (on success).
            error_code: MT5 error code (on failure).
        """
        if success:
            # Set success flag for StateManager to consume
            await self._redis.set("trade:result:success", "1")
        else:
            await self._redis.delete("trade:result:success")

        # Clear pending trade
        await self._redis.delete("trade:pending")
